- hosts: localhost
  name: Creando el modelo de datos por dispositivo
  gather_facts: no
  tags: [ model ]
  vars_files:
  - "prov-service-model/{{model|default('deploy-model.yaml')}}"
  tasks:
  - name: Creando el Device model basandonos en el Service model
    template: src=prov-service-model/deploy-model-to-device-data.j2 dest=./prov-data-model/deploy-model.cfg
    
    register: resultados_XR
  - debug: msg="{{ resultados_XR }}"
